### ISSUE TITLE
Use awscli and Terraform binaries in another image

### ISSUE THREAD

**Issue by Arnold1** [Zenika/terraform-aws-cli#32]
hi,

can I use the created binaries: aws, terraform also in 
```Linux dfbaae724a7a 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux``` ?

I tried:
```
#!/bin/bash

id=$(docker create zenika/terraform-aws-cli:latest)
docker cp $id:/usr/local/bin/aws - > ./bin/aws
docker cp $id:/usr/local/bin/aws.cmd - > ./bin/aws.cmd
docker cp $id:/usr/local/bin/aws_bash_completer - > ./bin/aws_bash_completer
docker cp $id:/usr/local/bin/aws_completer - > ./bin/aws_completer
docker cp $id:/usr/local/bin/aws_zsh_completer.sh - > ./bin/aws_zsh_completer.sh
docker cp $id:/usr/local/bin/terraform - > ./bin/terraform
docker rm -v $id
```

and added the bin folder to my golang:1.14 image (FROM golang:1.14)...

I get a this error:
```
bin# ./terraform 
bash: ./terraform: cannot execute binary file: Exec format error
```

**Comment by bgauduch** [comment]
Hello @Arnold1 !

Really sorry for the late answer !

The `awscli` and `terraform` binaries are installed on Debian buster in this repository.
So I doubt you can use them 'as-is' in your golang-based image (even more if it is the Alpine version), which is confirmed by the explicit error you get: binaries are not compatible with your base image.

I also wouldn't recommend to do that anyway, as it introduce external dependancies in your final image.

If I were you I would install  both the tools against your base image in your Dockerfile instead, to ensure it works as expected.
Feel free to inspire yourself from the way it's done in this repository [Dockerfile](https://github.com/Zenika/terraform-aws-cli/blob/master/Dockerfile), using multiple build stages 😉 

Hope this help, let me know if you manage to make this work !

**Comment by bgauduch** [comment]
Hello again @Arnold1 !

Did you manage to make this work ?

**Comment by bgauduch** [comment]
@Arnold1 closing this issue, feel free to comment again if needed !
